### ISSUE TITLE
OSGi and Maven version mismatch breaks the build

### ISSUE THREAD

**Issue by ldrozdz** [symphonyoss/symphony-rest-tools-ui#2]
mvn clean install

Failed to execute goal org.eclipse.tycho:tycho\-packaging\-plugin:1.0.0:validate-version(default-validate-version) on project org.symphonyoss.symphony.tools.rest.ui.console: Unqua

lified OSGi version 0.1.0.qualifier must match unqualified Maven version 0.1.2-SNAPSHOT for SNAPSHOT builds

**Comment by bruceskingle** [comment]
I was mid way through a release which caused this, I don't have time to finish the job now so I have merged this so the master branch builds in case anyone else looks immediately.

**Comment by bruceskingle** [comment]
When I say "merged this" I mean merged the PR which you raised to fix it.
